version: "3.6"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    container_name: events-app
    ports:
    - "8000:8000"
    working_dir: /events-app